macro(list_add_sources_multiarch list_var)
    set(sources "${ARGN}")
        set(${list_var}_COMMON)
        set(${list_var}_ARM)
        set(${list_var}_X86)
    foreach (source IN LISTS sources)
        get_filename_component(common_full "src/${source}" ABSOLUTE)
        get_filename_component(arm_full "sysspec/arm/${source}" ABSOLUTE)
        get_filename_component(x86_full "sysspec/x86/${source}" ABSOLUTE)

        if ("${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "ARM")
            if (EXISTS "${arm_full}")
                list(APPEND ${list_var} ${arm_full})
                list(APPEND ${list_var}_ARM ${arm_full})
            endif ()
        else ()
            if (EXISTS "${x86_full}")
                list(APPEND ${list_var} ${x86_full})
                list(APPEND ${list_var}_X86 ${x86_full})
            endif ()
        endif ()

        if (EXISTS "${common_full}")
            list(APPEND ${list_var} ${common_full})
            list(APPEND ${list_var}_COMMON ${common_full})
        endif ()
    endforeach ()
endmacro()